### ISSUE TITLE
AMD

### ISSUE THREAD

**Issue by disgracedmf** [rabume/cs2-dma-radar#17]
I am on AMD on both targated and attacking systems... Can't seem to get the cheat working. DMA leet. I want to try the radar in MM.

https://github.com/rabume/cs2-dma-radar/issues/13

This topic has the exact same problem as me. Seems like I can't also find mmap generator.

**Comment by xCorteX** [comment]
if u need mmap.txt generator 
i can send you one 


discord : killing1337
