### ISSUE TITLE
Need to update

### ISSUE THREAD

**Issue by HH333** [rabume/cs2-dma-radar#19]
Need to update

**Comment by HH333** [comment]
Offsets updated, but map and enemy location information cannot be loaded.

**Comment by rabume** [comment]
Hey, yeah, I know that the offsets are outdated. If you have updated them, I'm happy to merge your changes via a pr.
I don't know if I find time the next view days to make the changes myself.

**Comment by HH333** [comment]
Hello, I have updated the latest offsets but the map and radar cannot be loaded

**Comment by HH333** [comment]
dwEntityList: usize = 0x18B0FC8

dwLocalPlayerPawn: usize = 0x17262E8
