### ISSUE TITLE
Missing map

### ISSUE THREAD

**Issue by F0RSV1NNA** [rabume/cs2-dma-radar#2]
noticed Anubis was missing. 
also that sometimes things get mis-aligned and a little jittery maybe is the right word.
another good thing would be separating teammates by color ex : green blue yellow purple orange. 

will see if i can add anubis tomorrow.

**Comment by xCorteX** [comment]
Does anyone know where to get the coordinates for maps?

They are stored here in the radar, for example

de_dust2: {
map: de_dust2_radar,
bounds: [
[-127, -247],
[323, 202]
]
},

and in the game files
 
dust 2
"pos_x" "-2476" // upper left world coordinate
"pos_y" "3239"
"scale" "4.4"
"rotate" "1"
"zoom" "1.1"

**Comment by rabume** [comment]
- [ ] Add map support for Anubis

I noticed that it is jittery at times. I'll see if I can make any improvements to the performance. The idea of using colors to separate teammates is nice, but I wouldn't prioritize it.

**Comment by xCorteX** [comment]
I have already added Anubis and adjusted the coordinates so that they fit on the map. Here are the coordinates and the map

```
de_anubis: {
        map: de_anubis_radar,
        bounds: [
            [-200, -275],
            [333, 250]
        ]
```

![de_anubis_radar](https://github.com/rabume/cs2-dma-radar/assets/37551164/40645163-aeff-49da-abaa-128e6b797034)

**Comment by rabume** [comment]
Great! 👍 I will try to add it as soon as possible.

**Comment by Karky-io** [comment]
@xCorteX How did you go about finding the correct coordinates? I almost have office setup but can't get the enemy pawns to align properly.  Was there a trick that you found to making accurate adjustments?
