### ISSUE TITLE
Hello, where to find offset mapNameAddress?

### ISSUE THREAD

**Issue by extamyy** [rabume/cs2-dma-radar#21]
Where to find offset mapNameAddress?

app/src/main/java/cs2/dma/tuil/GameDataManager.java
mapName = memoryTool.readString(mapNameAddress + 0x4, 32);

I can update myself and compile the code, but where do I find offset so I can do this?

**Comment by rabume** [comment]
I do not know it myself yet. Will update as soon as I get it.

**Comment by xCorteX** [comment]
How did you come up with this offset?

I tried cheat angine but couldn't find it

**Comment by rabume** [comment]
Found it on a forum.

**Comment by xCorteX** [comment]
uc ?

**Comment by extamyy** [comment]
> uc ? Edit: I found out how ;) ![image](https://private-user-images.githubusercontent.com/37551164/303958719-00c552e6-2713-4db1-853d-cb625fec1e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTg2NTgsIm5iZiI6MTcwNzcxODM1OCwicGF0aCI6Ii8zNzU1MTE2NC8zMDM5NTg3MTktMDBjNTUyZTYtMjcxMy00ZGIxLTg1M2QtY2I2MjVmZWMxZTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA2MTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExOWE2YmUxMDE2N2Y2MWExNjgxYzM5ZDFjZTA1YzJiYzQ4ZmRmYjk3Y2U4ZWRkN2MyYmMzOWU2ODZmY2I4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUBlYhA_wxFwYL_wgp6_4tSlslZc4oH1JgGLmZf0qCU)

Hi, help me out with this, how did you find this offset?
Give me a guide on how you did it
