### ISSUE TITLE
request for adding the map/s!

### ISSUE THREAD

**Issue by HH333** [rabume/cs2-dma-radar#22]
Other maps are now missing after the update

**Comment by rabume** [comment]
Are you referring to the latest maps introduced in the arms race? Yes, they haven't been added yet.
If there are any other maps that are missing or not appearing, please inform me of the specific ones.

**Comment by rabume** [comment]
I figured out what's wrong. I accidentally committed some debug code which kept changing the map to dust2 all the time.
Try redownloading the latest [release](https://github.com/rabume/cs2-dma-radar/releases/tag/v1.1.3).

**Comment by HH333** [comment]
Thank you very much for your update, thank you
