### ISSUE TITLE
New Maps

### ISSUE THREAD

**Issue by xCorteX** [rabume/cs2-dma-radar#23]
![ar_shoots_radar_psd](https://github.com/rabume/cs2-dma-radar/assets/37551164/16f9a581-8cfb-4c17-8d2b-9a50f1f28e11)

```
"ar_shoots"
{
	"material"		"overviews/ar_shoots"
	"pos_x"		"-1368"
	"pos_y"		"1952"
	"scale"		"2.687500"
	"CTSpawn_x"		"0.520000"
	"CTSpawn_y"		"0.270000"
	"TSpawn_x"		"0.520000"
	"TSpawn_y"		"0.710000"
}

```
![ar_baggage_radar_psd](https://github.com/rabume/cs2-dma-radar/assets/37551164/37266877-5260-4076-ba88-9651f9e62dcc)
![ar_baggage_lower_radar_psd](https://github.com/rabume/cs2-dma-radar/assets/37551164/ca6dacec-7f58-4f48-a8ab-1da8acc15c36)

```
"ar_baggage"
{
	"material"		"overviews/ar_baggage"
	"pos_x"		"-1316"
	"pos_y"		"1288"
	"scale"		"2.539062"
	"rotate"		"1"
	"zoom"		"1.300000"

	"verticalsections"
	{
		"default" // use the primary radar image
		{
			"AltitudeMax" "10000"
			"AltitudeMin" "-5"
		}
		"lower" // i.e. de_nuke_lower_radar.dds
		{
			"AltitudeMax" "-5"
			"AltitudeMin" "-10000"
		}
	}


	"CTSpawn_x"		"0.510000"
	"CTSpawn_y"		"0.820000"
	"TSpawn_x"		"0.510000"
	"TSpawn_y"		"0.290000"
}
```

**Comment by rabume** [comment]
Thanks a lot :smile: 

I'll incorporate those soon. If you've already got them prepared and tested, feel free to submit a pull request—I'm more than happy to merge it. Thanks again!

**Comment by rabume** [comment]
@xCorteX 
[Added the maps](https://github.com/rabume/cs2-dma-radar/commit/21d97130e0db29085c07fb72b51ff0fd1d3ed2e4)

Had no time to test yet. If you have some spare time, you could pull this branch and test if the maps are working. The coordinates / dimension still need to be evaluated...

**Comment by xCorteX** [comment]
Unfortunately, I'll be very busy until the end of the week, after which I'll take up the topic

**Comment by Suspectxyzz** [comment]
@xCorteX do you have for dust2?
"pos_x","pos_y", ?

**Comment by rabume** [comment]
```
de_dust2: {
        map: de_dust2_radar,
        bounds: [
            [-127, -247],
            [323, 202]
        ]
    },
 ```

**Comment by Suspectxyzz** [comment]
> ```
> de_dust2: {
>         map: de_dust2_radar,
>         bounds: [
>             [-127, -247],
>             [323, 202]
>         ]
> }
> ```

can you help me with this? with my model 
[and now you can add offsets automatically with "mapnameval" it is updated automatically, now you don't have to use the cheat engine]  https://github.com/a2x/cs2-dumper/blob/d267a60b7da889cda4db6c47386520a47fd48272/generated/offsets.hpp#L57
{
	"scale": 4.4,
	"offset": {
		"x": -247,
		"y": 202
	},
	"splits": []
}

**Comment by xCorteX** [comment]
> can you help me with this? with my model

What do you mean exactly, these are the offsets for this radar, or tell me what doesn't work for you

Thanks for the offset, I'll integrate it

**Comment by xCorteX** [comment]
Maybe this will be of some help to you


```
{
    { "cs_italy",    (-2647f, 2592f, 4.6f) },
    { "cs_office",   (-1838f, 1858f, 4.1f) },
    { "de_ancient",  (-2953f, 2164f, 5f) },
    { "de_anubis",   (-2796f, 3328f, 5.22f) },
    { "de_dust",     (-2850f, 4073f, 6f) },
    { "de_dust2",    (-2476f, 3239f, 4.4f) },
    { "de_inferno",  (-2087f, 3870f, 4.9f) },
    { "de_mirage",   (-3230f, 1713f, 5f) },
    { "de_nuke",     (-3453f, 2887f, 7f) },
    { "de_overpass", (-4831f, 1781f, 5.2f) },
    { "de_vertigo",  (-3168f, 1762f, 4f) },
};
```

**Comment by Suspectxyzz** [comment]
> > can you help me with this? with my model
> 
> What do you mean exactly, these are the offsets for this radar, or tell me what doesn't work for you
> 
> Thanks for the offset, I'll integrate it
you can add me on discord so we don't spam, these offsets don't work for me
dsicord ->suspectxyz

**Comment by rabume** [comment]
Did you see the new release, @xCorteX? 
I have already merged my changes related to the new maps, but the position coordinates are not correct yet. If you have already evaluated the correct positions, I would love to merge your pull request.

**Comment by xCorteX** [comment]
I just calculated that it should work, I'll try it out afterwards, maybe a small correction needs to be made

```
    },
    ar_baggage: {
        needChangeMap: true,
        map: ar_baggage_radar,
        mapLower: ar_baggage_lower_radar,
        lowerValue: -480,
        bounds: [
            [-441, -131],
            [304, 369]
        ]
    },
    ar_shoots: {
        map: ar_shoots_radar,
        bounds: [
            [-372, -137],
            [128, 364]
        ]
    }
```

**Comment by rabume** [comment]
Thanks a lot :+1:
