### ISSUE TITLE
The map is not displayed, only the radar red dots are displayed

### ISSUE THREAD

**Issue by HH333** [rabume/cs2-dma-radar#24]
de_dust2 everything is normal     /  other   The map is not displayed, only the radar red dots are displayed

Please check for updates

**Comment by HH333** [comment]
Other competitive maps do not load, only radar red dots are displayed.

**Comment by rabume** [comment]
The issue should be resolved in the latest release. Please ensure to clear your browser cache (Ctrl+F5). Additionally, consider running the radar in an incognito window as an alternative solution.
