### ISSUE TITLE
Intialization Error 

### ISSUE THREAD

**Issue by Ikowuschkio** [rabume/cs2-dma-radar#25]
hey why i get this error ? 
![Screenshot_53](https://github.com/rabume/cs2-dma-radar/assets/160033563/18bb7483-93ba-4182-91e8-61ab00d37406)

**Comment by rabume** [comment]
Hey, because yesterday was an update and the offsets changed. Change the offsets in the config.json
```json
{
  "dwLocalPlayerPawn": "0x1729348",
  "dwEntityList": "0x18B3FA8"
}
```
I will also create a new release with the updated offsets soon.
