### ISSUE TITLE
Run jar successfully, open browser without map display

### ISSUE THREAD

**Issue by liar221100** [rabume/cs2-dma-radar#26]
hi,bro！According to the guide successfully run.jar, open the local browser 8080 page did not successfully display map and radar, may I ask how to solve this? thank you.

**Comment by rabume** [comment]
The offsets are outdated. You could just update the offsets in the `config.json` yourself.
I updated the current [release](https://github.com/rabume/cs2-dma-radar/releases/tag/v1.2.2) with the new offsets.
