### ISSUE TITLE
not working stomp js

### ISSUE THREAD

**Issue by extamyy** [rabume/cs2-dma-radar#27]
when I run the cheat, on localhost everything works, but when I run the localhost page on another computer, the page loads but the radar does not work (computers are connected to the same network).

I tried through ngrok the same thing happens, the page loads but radar does not work, I opened the console in the browser (f12), the error is related to stomp js (websocket).

**Comment by rabume** [comment]
Hey, I will check it out soon.

**Comment by rabume** [comment]
It appears that we're dealing with a CORS (Cross-Origin Resource Sharing) issue here. The browser is blocking the loading of external JavaScript resources when the connection is insecure.

During my testing, I accessed the external resources through ngrok, which establishes a secure SSL connection. To address this, I'll replace the JavaScript loaded from a CDN with a locally served one.

**Comment by rabume** [comment]
Works now without HTTPS / SSL. (CORS issue solved)
