### ISSUE TITLE
More Ticks

### ISSUE THREAD

**Issue by xCorteX** [rabume/cs2-dma-radar#3]
Is it possible to get more ticks? so that the picture runs more smoothly.

My DMA card manages 200 mb/s
or does the browser limit the ticks?

**Comment by rabume** [comment]
The ticks do not represent the MB/s that the card is currently using. Instead, they show you how long the average request takes to compute. Currently, it continually makes a request to an endpoint every 100ms, which is obviously not the best choice for performance.

**Comment by rabume** [comment]
Yes right here:

https://github.com/rabume/cs2-dma-radar/blob/main/client/src/components/Map.vue#L128

**Comment by xCorteX** [comment]
ty
