### ISSUE TITLE
Unable to use, please update

### ISSUE THREAD

**Issue by lum0022** [rabume/cs2-dma-radar#30]
I updated the base address, but when I opened the webpage, there was no map displayed

**Comment by rabume** [comment]
I'm sorry to hear that. I will try to work on it soon.

**Comment by lum0022** [comment]
I have reviewed the code,
D_iPawnHealth
D_iPawnArmor
M'bPawnIsAlive
M-angEyeAngles
M_iTeamNum
M_hPlayerPawn
M_vOldOrigin
Some addresses have changed, but I won't make any changes. Can you use the latest cs2 dumper format and update a version

**Comment by ffFliman** [comment]
m_angEyeAngles = 0x1570

**Comment by HH333** [comment]
> I'm sorry to hear that. I will try to work on it soon.
please update 
Thank you very much
