### ISSUE TITLE
Failed to initialize game data

### ISSUE THREAD

**Issue by RatGrease** [rabume/cs2-dma-radar#31]
After updating offsets and compiling, getting initialization error : failed to initialize game data. running DMA test shows that DMA can read from target PC so it's not a DMA connection issue

**Comment by ffFliman** [comment]
"dwLocalPlayerPawn": "0x173A3C8",
  "dwEntityList": "0x18C6268"  Everything works!

**Comment by rabume** [comment]
Thanks for the feedback @ffFliman 

Will update offsets this weekend and fix some issues I encountered, then release the new working version.

**Comment by RatGrease** [comment]
@ffFliman 
More than just the LocalPawn and EntityList offsets were changed with the last update, player looking direction also got changed. When I updated for the new offsets and recompiled, that is when the errors started.

**Comment by ffFliman** [comment]
@RatGrease

**Comment by HH333** [comment]
> 感谢您的反馈@ffFliman
> 
> 本周末将更新 offsets 并修复我遇到的一些问题，然后发布新的工作版本。

Thank you very much
