### ISSUE TITLE
The latest version still cannot be used

### ISSUE THREAD

**Issue by lum0022** [rabume/cs2-dma-radar#35]
Sorry to bother you, but today's game update seems to have changed the base address of the radar map. The browser opens with a white screen and there is no map available

**Comment by lum0022** [comment]
Is it a problem with my computer system? I reinstalled the system but still can't use it

**Comment by rabume** [comment]
I was not able to test my changes yet. For my understanding, only the offsets which can be changed in the offset.json had to be updated. Did you replace everything with the new release? Check the offset.json for this value:

```json
{
  "dwLocalPlayerPawn": "0x173D5A8",
  "dwEntityList": "0x18C9E78"
}
```

If it does not work, I will check later on my own system.

**Comment by lum0022** [comment]
> 我还无法测试我的更改。据我了解，只有 offset.json 中可以更改的偏移量才需要更新。您是否用新版本替换了所有内容？检查 offset.json 中的值：
> 
> ```json
> {
>   "dwLocalPlayerPawn": "0x173D5A8",
>   "dwEntityList": "0x18C9E78"
> }
> ```
> 
> 如果不起作用，我稍后会在我自己的系统上检查。

Yes, I replaced it. It shouldn't be an issue with offset.json

**Comment by rabume** [comment]
Alright, I will try it on my own system.

**Comment by ffFliman** [comment]
dwEntityList = 0x18C9E88

**Comment by ffFliman** [comment]
The map and players are not displayed, offsets have been updated. I don't know what's wrong( @rabume

**Comment by rossifl** [comment]
@ffFliman also having the same issue, updated the offsets but still no map or players, just the zoom and checkbox icons appear...

**Comment by rabume** [comment]
@ffFliman @lum0022 
So the offsets are updated. Also outsourced all offsets to the `offsets.json` file now.
So you can update it yourself in the future.
