### ISSUE TITLE
getting failed to initialize game data. 

### ISSUE THREAD

**Issue by RatGrease** [rabume/cs2-dma-radar#36]
offsets are current.

**Comment by RatGrease** [comment]
I have a feeling that with the newest cs2 update, vac now disables all non functional drivers. My DMA is shown as a raid controller on device manager; when I used different firmware that wasn't a fake broken driver, the radar would work.

**Comment by itsRiver** [comment]
I tested the radar with a DMA driver and with a fully broken one which has only errors, it works on both.

**Comment by rabume** [comment]
@itsRiver Thanks for your feedback.👌

@RatGrease I don't believe VAC currently has any countermeasures in place for DMA.
