### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by itsRiver** [rabume/cs2-dma-radar#38]
fixxed. Git bash was the solution.

Hello, suddenly i cannot build the project it says, before it was working.

"Build vite app..."
! was unexpected at this time.
make: *** [build] Error 255

Im pretty sure ive set the correct path, as it was working before. Any ideas? I tried older java sdk, older mvn, newer / older make.
(The release itself works) 

![error](https://github.com/rabume/cs2-dma-radar/assets/45321143/fefafbda-f45b-4ce6-afb6-c886b8877f05)
![path](https://github.com/rabume/cs2-dma-radar/assets/45321143/1c3e6697-4bbe-4a5b-8a53-6f88220a9c32)

**Comment by itsRiver** [comment]
Okay after 3 days ive fixxed it. I setup a vm and tried it with git and it installed some maven dependencies now it works.

**Comment by MaRf1Mm** [comment]
I'm adding to this because I wasted 30 minutes trying to find what you were referring to. Follow this guide to fix the Git Bash problem: https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058#make
