### ISSUE TITLE
The game has updated a new map, can you provide support

### ISSUE THREAD

**Issue by lum0022** [rabume/cs2-dma-radar#39]
Sorry to bother you, but today the game has updated a new map. Could you please add it? Thank you

**Comment by rabume** [comment]
Hey :wave: 
Will try to check it out this weekend.

**Comment by lum0022** [comment]
Thank you very much

**Comment by rabume** [comment]
@lum0022 Hey :wave: 
I haven't had a chance to check it out yet, but I will do so as soon as possible. In the meantime, if you have some free time, could you please provide me with the map assets? That would be greatly appreciated.

**Comment by lum0022** [comment]
![de_mills_radar](https://github.com/rabume/cs2-dma-radar/assets/160461751/73b67f35-188e-4c6e-b3ab-68636223a209)
![de_thera_radar](https://github.com/rabume/cs2-dma-radar/assets/160461751/dc4b63f0-1280-497d-9934-b91c30c87124)

**Comment by rabume** [comment]
Thanks alot :+1:

**Comment by rabume** [comment]
@lum0022 I updated the offsets. Also got all needed images. Still need to evaluate the bounds.

**Comment by lum0022** [comment]
Sorry, I don't know that, if you can teach me

**Comment by rabume** [comment]
I will make a release today with the updated offsets and maps. But until then just copy the content from [this](https://github.com/rabume/cs2-dma-radar/blob/main/release/offsets.json) file in your `config.json` file.

**Comment by lum0022** [comment]
Thank you, config.json. I will update it and look forward to your new version

**Comment by rabume** [comment]
@lum0022 
Here is the new [release](https://github.com/rabume/cs2-dma-radar/releases/tag/v1.2.6)
