### ISSUE TITLE
Hey yall instaled it on my laptop and all looks great. But if i share it with someone map does not work anymore.

### ISSUE THREAD

**Issue by MaRf1Mm** [rabume/cs2-dma-radar#41]
Main PC thro ngrok

![Main PC thro ngrok](https://github.com/user-attachments/assets/4113d71e-60aa-4582-b8a2-7b45db142358)

localhost laptop

![localhost laptop](https://github.com/user-attachments/assets/12d21e94-95c5-458d-82ff-b1a6b9dbbd73)

**Comment by MaRf1Mm** [comment]
i this will be up when you read it you can check it by yourself 
https://d478-2001-999-78c-d815-2091-2fc-2d48-ad35.ngrok-free.app

**Comment by MaRf1Mm** [comment]
Also i may be stupid so bear with me on this one

**Comment by MaRf1Mm** [comment]
Update: Something about the main PC not being able to connect to the websocket, but I'm not knowledgeable enough in Java to know what's wrong.

![image](https://github.com/user-attachments/assets/cb3bfa3f-0016-4d3a-8c03-741fa6121687)

I will leave ngrok page working so you can see it by yourself. Help will be appreciated.

**Comment by MaRf1Mm** [comment]
Also, your offsets are outdated. Here are the new ones below:

- "dwLocalPlayerPawn": "0x1824A18"
- "dwEntityList": "0x19BEED0"
- "dwGameTypes_mapName": "0x1A42E0"

**Comment by MaRf1Mm** [comment]
Replace lines 171, 172, 173 in `Map.vue` located at `"cs2-dma-radar-main\client\src\components\"` with the following:
```
const wsProtocol = location.protocol === 'https:' ? 'wss' : 'ws';
const wsHost = location.host;
const wsUrl = `${wsProtocol}://${wsHost}/radar`;
```
This WILL fix the issue.

Also, screw you for making me do this, as I wasted 4 hours of my life and learned JS to fix these 3 lines.

Additionally, the radar sometimes freezes; maybe optimize it or something, I don't know.

**Comment by rabume** [comment]
Hey @MaRf1Mm, thanks for providing the updated offsets. It looks like I [committed](https://github.com/rabume/cs2-dma-radar/issues/41#issuecomment-2266349920) a faulty component state during debugging. I'll revert to the commit where it was working, based on your example. I'll also explore some optimization possibilities.

**Comment by rabume** [comment]
Created new [release](https://github.com/rabume/cs2-dma-radar/releases/tag/v1.2.7) now.
