### ISSUE TITLE
cant open

### ISSUE THREAD

**Issue by Marino1235** [rabume/cs2-dma-radar#42]
i downloaded the latest zip, install everything and cant open it, i ran the command through nodejs, installed java development and nothing

**Comment by rabume** [comment]
Hey :wave: 
What exactly is the issue? Any specific error message?

**Comment by Marino1235** [comment]
can you help me through discord?

**Comment by Marino1235** [comment]
cant seem to run the radar

**Comment by Marino1235** [comment]
> Hey 👋 What exactly is the issue? Any specific error message?

cant managed to run the radar

**Comment by rabume** [comment]
This is not a specific error message...

Make sure to have installed this: https://adoptium.net/temurin/releases/?os=windows&arch=x64&package=jdk
and no other java installation. When installing, make sure that the box to override the JAVA path is set.

I just tested the latest version and everything works. I don't have time right now to give support over discord.

**Comment by Marino1235** [comment]
i dont know anything about this man, so complicated for someone that doesnt understand about java

**Comment by rabume** [comment]
You are trying to run a Java command in a Node.js terminal, you need to use CMD or PowerShell instead.

Download the latest release and install the Java version I mentioned earlier. Then, navigate to the directory where the cheat (.jar) file is located. Also, ensure you have the necessary drivers installed on your device (the computer you're using to run the cheat). 

The README might not be the most beginner-friendly, but you can always use ChatGPT or another LLM to get it working. 
If that's too much, consider buying a cheat instead.

I'll close this now.
