### ISSUE TITLE
 The game has been updated, please update the software

### ISSUE THREAD

**Issue by HH333** [rabume/cs2-dma-radar#43]
The game has been updated, please update the software

The radar map cannot be loaded

dwGameTypes_mapName =  0x120

**Comment by xCorteX** [comment]
Try dwGameTypes_mapName = 0x001A42C0

**Comment by SuperLifeown** [comment]
> New Offsets
> 
> ```
> {
>   "dwLocalPlayerPawn": "0x17CF698",
>   "dwEntityList": "0x1964198",
>   "dwGameTypes_mapName": "0x1A42C0",
>   "m_iPawnHealth": "0x7E8",
>   "m_iPawnArmor": "0x7EC",
>   "m_bPawnIsAlive": "0x7E4",
>   "m_angEyeAngles": "0x1388",
>   "m_iTeamNum": "0x3C3",
>   "m_hPlayerPawn": "0x7DC",
>   "m_vOldOrigin": "0x1274"
> }
> ```
> 
> I sent out a pull request

Do you all use ce software to find the offset one by one? I have a source code of pubg game cheating, but I don't know how to find the offsets. The current version can still be used, but after the game is updated, I am at a loss.

**Comment by xCorteX** [comment]
Cs2 Dumper
https://github.com/a2x/cs2-dumper
