### ISSUE TITLE
Role display issue

### ISSUE THREAD

**Issue by Snip1-99** [rabume/cs2-dma-radar#45]
I entered the correct offset, but I am unable to display my teammates and myself

{
  "dwLocalPlayerPawn": "0x17D47E0",
  "dwEntityList": "0x1969668,
  "dwGameTypes": "0x1A41A0",
  "dwGameTypes_mapName": "0x120",
  "m_iHealth": "0x324",
  "m_iPawnArmor": "0x7FC",
  "m_lifeState": "0x328",
  "m_angEyeAngles": "0x1388",
  "m_iTeamNum": "0x3C3",
  "m_hPlayerPawn": "0x7EC",
  "m_vOldOrigin": "0x1274",
  "m_iCompTeammateColor": "0x738"
}

**Comment by xCorteX** [comment]
`{
    "dwLocalPlayerPawn": "0x17D47E0",
    "dwEntityList": "0x1969668",
    "dwGameTypes": "0x1A41A0",
    "dwGameTypes_mapName": "0x120",
    "m_iHealth": "0x324",
    "m_iPawnArmor": "0x7FC",
    "m_lifeState": "0x328",
    "m_angEyeAngles": "0x1388",
    "m_iTeamNum": "0x3C3",
    "m_hPlayerPawn": "0x7EC",
    "m_vOldOrigin": "0x1274",
    "m_iCompTeammateColor": "0x738"
}`

works fine wor me on Matchmaking

**Comment by xCorteX** [comment]
OK, I know what you mean, that the standard icons are not displayed, I'll check it again today

**Comment by Snip1-99** [comment]
![2121](https://github.com/user-attachments/assets/30f90c44-caec-40f4-92cc-2061f3b63f6a)

**Comment by Snip1-99** [comment]
Like this, there are no teammates, only enemies

**Comment by rabume** [comment]
@xCorteX Thank you for your assistance. If you're unable to find time, I'd be happy to work on this over the weekend.

**Comment by xCorteX** [comment]
I can recommend you to use version **1.2.7** so that the normal game is displayed with standard icons. I just tried to fix the problem, but by adding deselecting every single icon there are complications when loading standard icons because the team ID number is requested becomes 


I will try to fix the problem as soon as I find time

**Comment by rabume** [comment]
@Snip1-99 Merged the changes from @xCorteX.
Built and created a new [release](https://github.com/rabume/cs2-dma-radar/releases/tag/v1.3.1).

@xCorteX I merged your changes for now. Will check if I can improve it later. Thanks again :pray:
