### ISSUE TITLE
Why am I unable to function properly?

### ISSUE THREAD

**Issue by LannYuu** [rabume/cs2-dma-radar#48]
I have installed all the necessary software, but there is still nothing on the webpage

![image](https://github.com/user-attachments/assets/c528e2e0-1713-42fe-96af-0e5bad19220e)
![image](https://github.com/user-attachments/assets/12c5c49b-e1bb-4b6e-a64e-f87c404abb7a)
![image](https://github.com/user-attachments/assets/faf11313-9f26-4233-8fc7-00d9c018b8d8)
![image](https://github.com/user-attachments/assets/2887de6c-dcb3-4999-b33c-f7977384371f)

**Comment by xCorteX** [comment]
you have to update the offsets yourself 


![IMG_0911](https://github.com/user-attachments/assets/0e0e2a9e-dd40-4a3c-bb1f-167e0f347420)
