### ISSUE TITLE
Hello, the game has been significantly updated, and the software needs to be updated

### ISSUE THREAD

**Issue by HH333** [rabume/cs2-dma-radar#49]
Hello, the game has been significantly updated, and the software needs to be updated

**Comment by rabume** [comment]
Will try to update soon

**Comment by HH333** [comment]
> Will try to update soon

Thank you very much

**Comment by xCorteX** [comment]
update the offsets ant it work agin

{
"dwLocalPlayerPawn": "0x18220C8",
"dwEntityList": "0x19BAC58",
"dwGameTypes": "0x1A31B0",
"dwGameTypes_mapName": "0x120",
"m_iHealth": "0x344",
"m_iPawnArmor": "0x81C",
"m_lifeState": "0x348",
"m_angEyeAngles": "0x1430",
"m_iTeamNum": "0x3E3",
"m_hPlayerPawn": "0x80C",
"m_vOldOrigin": "0x131C",
"m_iCompTeammateColor": "0x758"
}

**Comment by rabume** [comment]
Test the latest release: [v1.3.2](https://github.com/rabume/cs2-dma-radar/releases/tag/v1.3.2)
