### ISSUE TITLE
[Feature] Automatically launch after restarting the game client

### ISSUE THREAD

**Issue by Jackjun724** [rabume/cs2-dma-radar#57]
In the Chinese battle platform, cs2.exe will be closed after each game, is there a plan to support state cycling?

If you don't have much time, I'm willing to do something for this.

**Comment by rabume** [comment]
Hey, I see what you mean. I think I could add handling for such cases. The client doesn’t change names right after every start, does it? I think some anti-cheats do that.

**Comment by Jackjun724** [comment]
Anti-cheating does not change the name of the client process. In China, the competition process is carried out on a third-party platform, where cs2 is started through parameters after matching, and cs2 is closed after the game ends, and then the third-party platform is used to match opponents again. 

Happy to be of service :)

**Comment by Hogwarts-0** [comment]
> 嘿，我明白你的意思。我想我可以添加针对此类情况的处理。客户端不会在每次启动后立即更改名称，对吗？我认为有些反作弊软件会这样做。

The Perfect World competitive platform will not change its name, but the 5E battle platform will change the cs2 process name every time the game is started

**Comment by rabume** [comment]
@Hogwarts-0 Ah yes, that's what I meant.

**Comment by rabume** [comment]
I added a very simple game state handling. Let me know if this is enough for you. I'm open for pr's with improvements.
@Hogwarts-0 For now I added no handling for random cs2 instance names.

**Comment by Hogwarts-0** [comment]
> 我添加了一个非常简单的游戏状态处理。如果这对您来说足够了，请告诉我。我愿意接受改进。 @Hogwarts-0目前我没有添加对随机 cs2 实例名称的处理。

OK, I will test it as soon as possible and give you feedback. Thank you for your attention to my feedback.
