### ISSUE TITLE
Issues below

### ISSUE THREAD

**Issue by yahur** [rabume/cs2-dma-radar#62]
Hi guys currently getting these issues with no avail.
![image](https://github.com/user-attachments/assets/78d86138-a8a1-4807-bc52-82077e56dcef)
![image2](https://github.com/user-attachments/assets/5b36d0c9-b231-4499-a100-3d27d246df72)

**Comment by yahur** [comment]
I also added the new offsets myself but still getting issues

**Comment by yahur** [comment]
![image](https://github.com/user-attachments/assets/6ad2129a-b346-4cb5-9612-09a1d793988a)
I now get this, it's a step in the right direction but not getting any connection at port 8080

**Comment by rabume** [comment]
Hey, I will try to reproduce this weekend.

**Comment by ffFliman** [comment]
I have the same problem

**Comment by rabume** [comment]
ok, I check soon

**Comment by rabume** [comment]
I updated the offsets.
