### ISSUE TITLE
Update frontend

### ISSUE THREAD

**Issue by rabume** [rabume/cs2-dma-radar#7]
Improve the map to make it cleaner and include more information.

Insperation:
https://github.com/clauadv/cs2_webradar/tree/main

![image](https://github.com/rabume/cs2-dma-radar/assets/19410629/8ee19cd7-1b72-4d04-8cc1-f8762b7e5af5)

**Comment by C0DE4ME** [comment]
wow that would look so nice
amazing simple project btw, this is exactly what i was looking for

**Comment by xCorteX** [comment]
If you could make it DMA capable that would be nice
