### ISSUE TITLE
Update offsets

### ISSUE THREAD

**Issue by rabume** [rabume/cs2-dma-radar#9]

**Comment by Karky-io** [comment]
It appears that the characters orientation does not rotate in these last few updates.  I've tried messing around with a few offsets but can't seem to get it right....

**Comment by rabume** [comment]
Yeah, I know. Please give me some time, I'll try to do it over the weekend.

**Comment by Karky-io** [comment]
I got it working by adding the updated m_angEyeAngles offsets.

In the PlayerUpdateAddressThread.java file, update to:

line 84 ;    ` 90 - memoryTool.readFloat(Pawn + 0x1510 + 0x4, 8), `
line 87 ;      `float angle = memoryTool.readFloat(LocalPlayerController + 0x1510 + 0x4, 8) - 90; `
line 110 ;     `90 - memoryTool.readFloat(Pawn + 0x1510 + 0x4, 8) + angle, `

**Comment by rabume** [comment]
Done! Thanks @Karky-io
